### ISSUE TITLE
Empty <title>-tag with WordPress 4.4

### ISSUE THREAD

**Issue by p-volk** [davidakennedy/accessible-zen#70]
Hi David,

yesterday I've upgraded WordPress to version 4.4 After the upgrade the front page's title tag was empty. My current workaround for this issue is removing the title tag from header.php
```diff
diff --git a/htdocs/wp-content/themes/accessible-zen/header.php b/htdocs/wp-content/themes/accessible-zen/header.php
index 14d975b..e716ed9 100755
--- a/htdocs/wp-content/themes/accessible-zen/header.php
+++ b/htdocs/wp-content/themes/accessible-zen/header.php
@@ -15,7 +15,6 @@
 <head>
 <meta charset="<?php bloginfo( 'charset' ); ?>" />
 <meta name="viewport" content="width=device-width" />
-<title><?php wp_title( '|', true, 'right' ); ?></title>
 <link rel="profile" href="http://gmpg.org/xfn/11" />
 <link rel="pingback" href="<?php bloginfo( 'pingback_url' ); ?>" />
 <!--[if lt IE 9]>
```

I guess this is somehow related to: [Document title in 4.4](https://make.wordpress.org/core/2015/10/20/document-title-in-4-4/).

**Comment by davidakennedy** [comment]
Thanks for filing the issue @p-volk!

I've pushed up a fix in the `dev` branch. You can download it here if you need it: https://github.com/davidakennedy/accessible-zen/tree/dev

I hope to have a new release with this fix submitted to WordPress.org within the next week. I meant to do this earlier, but got behind on things, so thanks again for the nudge. :smile:
